<?php

namespace Drupal\sigma_payment\Services;

interface SigmaCardManagerInterface {

  /**
   * Create a new Card and set in the customer
   * @param $uid
   *    User ID ( Drupal )
   * @param $card_name
   *    Card name owner
   * @param $card_number
   *    Card number
   * @param $expiration_card
   *    Expiration card (MMYY)
   * @param $cvv
   *    Card verification code
   * @return mixed
   */
  public function addCard($uid, $card_name, $card_number, $expiration_card, $cvv);

  /**
   * Update status card
   *
   * @param $uid
   *    User ID ( Drupal )
   * @param $token_card
   *    A unique token generated by the SIGMA GATEWAY API.
   * @param $status
   *    New status: Active/Inactive
   * @return mixed
   */
  public function updateStatusCard($uid, $token_card, $status);
}
