<?php


namespace Drupal\sigma_payment\Services;


interface SigmaTransactionManagerInterface {

  /**
   * Perform Sale transaction using Customer’s information.
   *
   * @param $uid
   *   User ID ( Drupal )
   * @param $order_id
   *   Order ID.
   * @param $token_card
   *  Token card
   * @param $amount
   *  Amount to paid.
   * @param $currency
   *
   * @return mixed
   */
  function saleTransaction($uid, $order_id, $token_card, $amount, $currency);

  /**
   * Search transaction.
   * @param $transaction_id
   *    A unique token generated by the SIGMA GATEWAY API
   *
   * @return mixed
   */
  function searchTransaction($transaction_id);

  /**
   * Refunds approved  Sale transaction  using referenceSaleTransaction ID.
   * Refunds  on  the same  day original  Sale  happened  effectively  void
   * the  transaction  without  impact  on  the  cardholder’s account;
   * on the other hand Refunds on the day after original Sale happened
   * generate a credit operation to the cardholder, noticeable in their
   * bank account statement.
   *
   * @param $transaction_id
   *    A unique token generated by the SIGMA GATEWAY API
   * @param $amount
   *    Amount to paid.
   *
   * @param $currency
   *
   * @return mixed
   */
  function refundTransaction($transaction_id, $amount, $currency);
}
