commerce_payment.commerce_payment_gateway.plugin.sigma_payment_onsite:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant Id'
    terminal_id_colones:
      type: string
      label: 'Terminal Id Colones'
    terminal_id_dollars:
      type: string
      label: 'Terminal Id Dollars'
    merchant_id_sandbox:
      type: string
      label: 'SANDBOX Merchant Id'
    terminal_id_sandbox:
      type: string
      label: 'SANDBOX Terminal Id'
